name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2

      - name: Install latest stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt,clippy

      - name: Run rustfmt
        run: cargo fmt --all --check

      - name: Run clippy
        uses: giraffate/clippy-action@v1
        with:
          github_token: ${{ github.token }}
          clippy_flags: --all-features
          reporter: github-pr-check

      - name: Run tests
        run: cargo test --all-features

  deploy:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'release' }}
    needs:
      - checks
    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2

      - name: Install latest stable
        uses: dtolnay/rust-toolchain@stable

      - name: Log into crates.io
        run: cargo login ${{ secrets.CRATES_IO_TOKEN }}

      - name: Publish to crates.io (ruice)
        run: cargo publish --allow-dirty -p ruice

      - name: Publish to crates.io (ruice-axum)
        run: |
          until cargo publish --allow-dirty -p ruice-axum
          do
            echo "Still waiting..."
            sleep 5
          done
